//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ProisoCortex
{
    
    public class Sucursal
    {
        public int idsucursal { get; set; }
        public string sucursal1 { get; set; }
        public string representante { get; set; }
        public string direccion { get; set; }
        public string rfc { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> sucursalactiva { get; set; }
    }
}
