//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProisoCortex
{
    using System;
    using System.Collections.Generic;
    
    public class Venta
    {
        public int idventa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> cambio { get; set; }
        public Nullable<int> idmoneda { get; set; }
        public Nullable<int> idticket { get; set; }
        public Nullable<int> iddespechador { get; set; }
        public Nullable<int> idisla { get; set; }
        public Nullable<int> idbomba { get; set; }
        public Nullable<int> idmanguera { get; set; }
    }
}
